version: '3.9'

services:
  # MongoDB Service
  mongo_db:
    container_name: mongo_db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  # Ecommerce Backend - User Service API
  api:
    build: .
    ports:
      - 4001:3001
    environment:
      PORT: 3001
      MONGO_URL: mongodb://mongo_db:27017
      ACCESS_TOKEN_SECRET: 12345
      ADMIN_VERIFICATION_TOKEN_SECRET: 67890
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
    

